### ISSUE TITLE
The cwd for nur process could be $nur.run-path instead of $nur.project-path

### ISSUE THREAD

**Issue by kjelly** [ddanier/nur#27]
**Describe the bug**
The cwd for nur process could be $nur.run-path instead of $nur.project-path
If I create new tmux pane from the pane which is used for running nur process, I can get the new pane whose pane cwd is $nur.run-path

**To Reproduce**
```
.
├── a
├── b
└── nurfile
```
When I run nur in a directory, the nur process cwd is $nur.project-path instead of $nur.run-path (In a directory)

**Expected behavior**

I prefer use $nur.run-path. So I can create new tmux pane from nur process pane without extra cd command. 
Or make the behavior configurable

**Comment by ddanier** [comment]
@kjelly Actually this is a feature of `nur`, see the README:

> `nur` tasks will always be run inside the directory the file `nurfile` was found in.

As `nur` is meant to support you working on any project it is essential for the tasks to be executed in a well defined environment. Running the tasks in `$nur.project-path` is part of this well defined environment - as now it does not matter in which sub-directory in your project you are, you can still always do things like `cd src/` in your tasks and it will work as expected. This means starting the tasks in `$nur.project-path` is part of the "contract" `nur` will comply with. It's an essential part of what `nur` want to do and in my opinion just the better default for most use cases.

Having all that said you can always just start your tasks with something like `cd $nur.run-path`. I have done this myself as I have a "global" `nurfile` living in `$HOME`. All my tasks there start with `cd $nur.run-path` for example.

**Comment by ddanier** [comment]
Additional note: This cannot be changed without breaking most of the current tasks for people (in a kind of random manner).

**Comment by kjelly** [comment]
Thank for your reply.
I will use the following code for my usecase
```
def r [ task:string@"nu-complete nur task-names" ] {
  let code = "import os\nos.system('nur " + $task + "')"
  python3 -c $code
}
```
