### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by bambamboole** [ddanier/nur#4]
Hey mate, can we get some simple installation docs please ?

Ideally also for development ;)

**Comment by ddanier** [comment]
@bambamboole I hope this helps:
https://github.com/ddanier/nur?tab=readme-ov-file#installing-nur

Thanks for the hint this is missing. I just used `cargo` for everything and never though about others not knowing how to handle rust packages.

Of course you need to have `cargo` installed - as of now.

See https://doc.rust-lang.org/cargo/getting-started/installation.html for details.

**Comment by ddanier** [comment]
I will close this issue, as it has been resolved :)

**Comment by bambamboole** [comment]
Awesome! thank you!
